---
title: "Uso de internet mundial"
format: html
editor: visual
---

## PAQUETES Y DATOS
```{r}
library(tidyverse)
library(janitor)
library(stringi)
```


```{r}
path_int = "../data/internet_users_world_wide.csv"
internet = read_csv(path_int, skip = 4)

path_met = "../data/metadata_countries_internet_users.csv"
metadata = read_csv(path_met)
```

## 1. NORMALIZAR DATOS
```{r}
#Funcion para normalizar los datos
funcion_df = function(dataframe, clean = TRUE, which_remove = "cols") {
  if (clean) {
    data_clean = clean_names(dataframe)
  } else {
    data_clean = dataframe
  }
  
  if (which_remove == "both") {
    data_clean = data_clean |> 
      janitor::remove_empty(which = 'cols') %>% 
      janitor::remove_empty(which = 'rows')
  } else {
    data_clean = janitor::remove_empty(data_clean, which = which_remove)
  }
  
  return(data_clean)
}

funcion_df(internet, clean = FALSE, which_remove = 'both')
```

```{r}
#Normalizar datos
internet <- funcion_df(internet)
metadata <- funcion_df(metadata)
```

## 2. PIVOTEO
```{r}
# Pasar la tabla a formato long
internet_long <- internet %>%
  pivot_longer(
    cols = starts_with("x"),
    names_to = "year",
    values_to = "internet_users")
```

```{r} 
# Saco las x de year
internet_long = internet_long |>
  mutate(year = as.numeric(gsub("x", "", year)))
```

## 3. TRATAMIENTO DE NAs
```{r}
# Limpieza de NA
internet_long <- internet_long %>%
  filter(!is.na(internet_users))
```

## 4. CRUCE DE DATOS
```{r}
# Cruzar los datos de ambas tablas, segun el nombre de las variables iguales
datos_df = internet_long |> 
  left_join(metadata, by = c("country_name" = "table_name","country_code" = "country_code"))
```

## 5. AGREGACION
```{r}
# Calcular las metricas para la tabla
hipotesis <- datos_df |> filter(year >= 2013 & year <=2023) |> filter(income_group %in% c("Low income", "Lower middle income", "Upper middle income", "High income")) |>
group_by(region, year, income_group) |> 
  summarize(
    promedio_internet = mean(internet_users, na.rm = TRUE),
    .groups = "drop")
```

## CREACION DE TABLA PARA EL ENTREGABLE FINAL
```{r}
# Armar tabla inicial, dividida por nivel ingreso
hipotesis_final <- datos_df |>
  filter(
    year >= 2013 & year <= 2023,
    income_group %in% c(
      "Low income",
      "Lower middle income",
      "Upper middle income",
      "High income")) |>
  group_by(year, income_group) |>
  summarize(
    promedio_internet = mean(internet_users, na.rm = TRUE),
    .groups = "drop")
```

```{r}
# Pivotear a formato wide
hipotesis_final <- hipotesis_final |>
  pivot_wider(
    names_from = income_group,
    values_from = promedio_internet)
```

```{r}
# Agregar a la tabla el normbre del indicador
hipotesis_final <- hipotesis_final |>
  mutate(
    indicator_name = "Proporción de la población que usa internet (%)")
```


